export default {
  buttons: '버튼',
  'icon-buttons': '아이콘 버튼',
  inputs: '입력',
  controls: '컨트롤',
  feedback: '피드백',
  dialog: 'Dialog',
  select: 'Select',
  dropdown: 'Dropdown',
  picker: 'Picker',
  content: '콘텐츠',
  chips: 'Chip',
  'segmented-control': 'SegmentedControl',
  tab: 'Tab',
  table: '테이블',
}
